### ISSUE TITLE
Any idea why this regex isn't working?

### ISSUE THREAD

**Issue by alexklibisz** [beautiful-scala/sbt-scalastyle#48]
Hi, thanks for picking up the maintenance of this project. I have a question that's hopefully just a matter of me being ingorant on how regular expressions work.

I'm trying to emit a scalafix warning when people `throw` exceptions.

Right now I have this:

```
<check enabled="true" class="org.scalastyle.scalariform.TokenChecker" level="error">
        <parameters>
            <parameter name="regex">throw</parameter>
        </parameters>
        <customMessage>Avoid throwing exceptions. Instead, use error-handling constructs: Try, Future, Either, etc..</customMessage>
    </check>
```

And it works for `throw new Exception(...)`. Unfortunately it also matches `def throwUsedInSomeOtherWay`.

I've also tried the same regex with the `RegexChecker`.. but then that also matches comments, e.g. `// I'm not throwing an exception`.

I've also tried variations of the regex, e.g. `throw\b` indicating that there should be a single word, and `throw$` because that's what's used in the docs. But then it doesn't match anything.

**Comment by mwz** [comment]
Yeah, it looks like you figured this out already in your PR.
The `TokenChecker` regex only works across `VARID` tokens and it doesn't match the `throw` keyword, for which you need to implement a new `AbstractTokenChecker`, which is exactly what you did.

Thanks, your PR looks good - I'll merge and release shortly.

**Comment by mwz** [comment]
closed by https://github.com/beautiful-scala/scalastyle/pull/83
